### ISSUE TITLE
Error in using

### ISSUE THREAD

**Issue by alienatorZ** [davenquinn/cesium-martini#18]
Hello I tried to use this library but I am receiving this error in the browser.  How could I fix?

index.cjs:14 Uncaught ReferenceError: __dirname is not defined
    at node_modules/@macrostrat/cesium-martini/node_modules/cesium/index.cjs (index.cjs:14:3)
    at __require2 (chunk-OZI5HTJH.js?v=df6a9d37:15:50)
    at node_modules/@macrostrat/cesium-martini/dist/index.js (index.cjs:16:2)
    at __require2 (chunk-OZI5HTJH.js?v=df6a9d37:15:50)
    at terrain-provider.ts:315:52

**Comment by alienatorZ** [comment]
I am running with Resium and vite..

**Comment by davenquinn** [comment]
This should now be fixed by #19
